Remove main from the script test.
On Windows, Bazel passes additional non-absl googletest command line flags to death-tests,
specifically --gtest_filter and --gtest_internal_run_death_test. In order for
these flags to be properly parsed, the order of initialization in the main function
needed to be carefully arranged. The current code

```
fst::InitOpenFst(argv[0], &argc, &argv, true);
::testing::InitGoogleTest(&argc, argv);
return RUN_ALL_TESTS();
```

actually fails for all the death tests, example:

```
2026-03-07T19:17:55.7739206Z openfst/test/script_test.cc(214): error: Death test: VectorFstClass vfc(kDummyName)
2026-03-07T19:17:55.7751689Z     Result: died but not with expected error.
2026-03-07T19:17:55.7760030Z   Expected: contains regular expression "Unknown arc type: nonexistent"
2026-03-07T19:17:55.7761866Z Actual msg:
2026-03-07T19:17:55.7763578Z [  DEATH   ] ERROR: Unknown command line flag 'gtest_filter'
2026-03-07T19:17:55.7769252Z [  DEATH   ] ERROR: Unknown command line flag 'gtest_internal_run_death_test'
2026-03-07T19:17:55.7778949Z [  DEATH   ]
2026-03-07T19:17:55.7779583Z
2026-03-07T19:17:55.7780831Z [  FAILED  ] ClassTest.VectorFstClassConstructAndCopy (15 ms)
```

while the following (removing the unknown flags by `fst::InitOpenFst`
succeeds):

```
::testing::InitGoogleTest(&argc, argv);
fst::InitOpenFst(argv[0], &argc, &argv, true);
return RUN_ALL_TESTS();
```

Rather than dealing with this brittle behavior, simply rely on the main
provided by the googletest.

PiperOrigin-RevId: 880216018