Introduce WIN32-specific APIs to generic-registerer.
This placates the build:

```
openfst/lib/generic-register.cc(20): fatal error C1083: Cannot open include file: 'dlfcn.h': No such file or directory
```

PiperOrigin-RevId: 887414419